app:
  title: 欢迎使用 in 东师
  content: 欢迎使用 in 东师。这是一个由 Mr.Hope 个人制作的非官方小程序，内含 82 万字的新生攻略。希望大家能够通过小程序摆脱对大学的迷茫。
account:
  title: 账号存储说明
  content: 您输入的账号信息仅会存储于本地，并在您删除小程序、清除微信缓存卸载微信时移除。开发者不会读取、上传您的个人信息。当且仅当您需要登录时，我们会读取您本地的账号密码，并直接转发至相关登录服务。
  force: true
