# 上次更新于 8/27 12:37
all: 1520
donations:
  - - noveau
    - 227.48
  - - 悠然
    - 20
  - - 妖精哪里跑
    - 2
  - - 红鼻子小黑
    - 8
  - - Administrator
    - 39.68
  - - 天天发财
    - 6
  - - WANG-
    - 8
  - - opviuivqo
    - 2
  - - 黄浦妹妹
    - 50
  - - 是小明啊
    - 8.8
  - - 寒冬为阳
    - 18
  - - Alory
    - 2
  - - 社会你龙哥
    - 20
  - - 杨家有女初长成
    - 6
  - - 柳棉
    - 2
  - - crq007
    - 100
  - - 甲
    - 6
  - - 旧时光无尽夏.
    - 6.66
  - - 山高路远再见
    - 2
  - - 洛白
    - 19.85
  - - 灰灰美甲
    - 6
  - - 朝夕
    - 16
  - - 25℃
    - 2
  - - pro
    - 18
  - - 金银花
    - 6
  - - 木子
    - 8
  - - 刘笑爽
    - 14
  - - ZFQ
    - 8
  - - Mr.白告
    - 2
  - - 孙于程
    - 6
  - - 肖春梅
    - 8
  - - 悠然
    - 2
  - - 莉
    - 8
  - - 七
    - 6
  - - 慧慧
    - 18
  - - Long07744168
    - 18
  - - 初夏
    - 18
  - - 冰琳
    - 2
  - - nicole
    - 2
  - - و
    - 100
  - - 初夏
    - 18
  - - 遇事不决睡大觉
    - 18
  - - 小金睡不醒Zzz
    - 32
  - - 日不落星球
    - 2
  - - 羊咩咩
    - 6
  - - 兔斯基
    - 2
