title: 首页
id: main
grey: true
hidden: true
content:
  - tag: card
    cover: http://mmbiz.qpic.cn/mmbiz_jpg/ic9k8LCTbicc7fibAYDFBn7oAvOaEs00iblrOKaFWoIrqzQzoXXDPmHNjS9bm9ZUVQWB3149EYsjmQNS4jU1HzUW5Q/0?wx_fmt=jpeg
    title: 小程序封停以及整改声明
    logo: $img/inNENU.png
    name: in 东师
    url: info?path=Oabout/change-notice

  - tag: grid
    header: 入校介绍
    items:
      - text: 寝室
        color: blue
        name: Dorm
        icon: dorm
        path: guide/dorm/

      - text: 超市
        color: olive
        name: Shop
        icon: shop
        path: guide/shop/

      - text: 洗浴
        color: red
        name: Bath
        icon: bath
        path: guide/bath/

      - text: 校园卡
        color: red
        name: Card
        icon: card
        path: guide/card/

      - text: 校园网
        color: purple
        name: Network
        icon: network
        path: guide/network/

  - tag: grid
    header: 了解学习
    items:
      - text: 专业介绍
        color: olive
        name: Major
        icon: about
        path: intro/school/major

      - text: 转专业
        color: red
        name: Change Major
        icon: change
        path: guide/change-major/

      - text: 师范生
        color: purple
        name: Normal
        icon: teacher
        path: guide/normal/

      - text: 课程
        color: orange
        name: Course
        icon: content
        path: guide/course/

      - text: 学习
        color: mauve
        name: Study
        icon: study
        path: guide/study/

      - text: 选课
        color: cyan
        name: Select
        icon: select
        path: guide/select/

      - text: 图书馆
        color: blue
        name: Library
        icon: library
        path: intro/apt/library/

      - text: 考试
        color: olive
        name: Test
        icon: test
        path: guide/test/

    footer: 更多内容请详见下方其他 Tab 页
