app:
  title: 欢迎使用 in 东师
  content: 欢迎使用 in 东师。这是一个由 Mr.Hope 个人制作的非官方小程序，内含 74 万字的新生攻略。希望大家能够通过小程序摆脱对大学的迷茫。

guide/shop/jingyue:
  title: 营业时间
  content: |-
    11:30-13:00 16:30-18:30 暂停营业
  force: true

guide/life/dining2-district:
  title: 营业时间
  content: |-
    11:30-13:00 16:30-18:30 暂停营业
  force: true
