app:
  title: 欢迎使用『东师青年+』
  content: 欢迎使用东师青年+。这是一个由校团委融媒体中心授权 Mr.Hope 个人开发制作的小程序，内含 82 万字的新生攻略。小程序内容仅代表 Mr.Hope 的个人观点，希望大家能够通过小程序摆脱对大学的迷茫。
select:
  title: 已知问题
  content: 目前搜索结果中自己已选课程仍会显示选课按钮，但点击后会显示与同名课程冲突。如需退课请切换到课表并点击课程进行退课。
  force: true
